cache:
  directories:
  - Carthage

before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - carthage bootstrap --verbose --no-use-binaries --cache-builds

install:
- carthage bootstrap

matrix:
  include:
    - os: osx
      osx_image: xcode9.3
      language: objective-c
      script: xcodebuild clean test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X,OS=11.3' -workspace Flint.xcworkspace -scheme FlintCore-iOS CODE_SIGNING_REQUIRED=NO
      env:
        - _FLAVOUR=iOS
    - os: osx
      osx_image: xcode9.3
      language: objective-c
      script: xcodebuild clean test -sdk appletvsimulator -destination 'platform=tvOS Simulator,name=Apple TV,OS=11.3' -workspace Flint.xcworkspace -scheme FlintCore-tvOS CODE_SIGNING_REQUIRED=NO
        - _FLAVOUR=tvOS
    - os: osx
      osx_image: xcode9.3
      language: objective-c
      script: xcodebuild clean build -sdk watchsimulator -destination 'platform=watchOS Simulator,name=Apple Watch - 42mm,OS=4.3' -workspace Flint.xcworkspace -scheme FlintCore-watchOS CODE_SIGNING_REQUIRED=NO
        - _FLAVOUR=watchOS
    - os: osx
      osx_image: xcode9.3
      language: objective-c
      script: xcodebuild clean test -sdk macosx -workspace Flint.xcworkspace -scheme FlintCore-macOS CODE_SIGNING_REQUIRED=NO
        - _FLAVOUR=macOS

notifications:
  email: false
  slack:
    secure: fncX9S6zVun/V3fa+3spchQjkqeuXiJCoTzVuhf/4vNJ/FREF/cHagKmM+riuZaJMk08F0IAUy5KPKKQHubGvxT1tLfxr3LnEHrfYJXAIdcsVBFXetE+xYbPahNK5yhWm7QjUzKFvUBlvCsprErP+sjUvPhcA4MlSaa659gecVnXQuQ8YQcl/bOxvJIKcUYCBqwKxREf8WEALrKx07IDRZH+t/lYUZ8TDD+cawCGl1ZcPearV7pw6M8YBPNrXbqqlERggzlBWYFOmZkb09GsUGEW5nkSnbD2S5ywszLFNIxdyZuOmeSjtK8jYwl9dlpU2dzAXMGXB+VW7BOC5cQpuxkUiGQzZVKAC6leJs/AD3GFXGGWIzeXWXQN6bkvfHlMtD1GRTy1RYI4yb/UrMnWOoGxIfz6Hk1qVn5C2DL5g3Odbg1m8mk4Q731x67bhzMNY7KgjvJFbsObwJgUTprZQmkfAT7yxRxjhEeoHpK9kgXD96IfiZDdzh5l+tcVAWmwY2Zg+0J/Lma5tud4zK/t+BoBTdhVw0aoCVCACKlWhJOoScIxpuPUmcePGo8eR57YG8q1f/8daRFuy3Q9sxfCdlDAsh6AKyseZ4RyYSn9jIYpd0d51/vqdtrhRYNmOBdmcyRJfGCgrNjdHR/XwS9gIHUUBsHDz/Cv64rGjnlza4s=
